name: Conditional Scheduled Pipeline vol3

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 16 * * *'  # Runs at 10:00 PM IST (4:30 PM UTC)

jobs:
  set-push-flag:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Get current time in IST
        run: |
          CURRENT_HOUR=$(TZ=Asia/Kolkata date +%H)
          if [ $CURRENT_HOUR -ge 9 ] && [ $CURRENT_HOUR -lt 20 ]; then
            echo "Push happened between 9 AM and 8 PM IST"
            echo "push_detected=true" > push_flag.txt
          else
            echo "Push outside the allowed time window, skipping flag creation."
          fi

      - name: Upload push flag
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: push-flag
          path: push_flag.txt
          retention-days: 1  # Store flag only for today

  run-pipeline:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Download push flag
        uses: actions/download-artifact@v4
        with:
          name: push-flag
        continue-on-error: true  # Don't fail if artifact is missing

      - name: Check if push happened in the time range
        run: |
          if [ ! -f push_flag.txt ]; then
            echo "No push between 9 AM and 8 PM IST. Skipping workflow."
            exit 0
          fi

      - name: Execute pipeline
        run: echo "Executing scheduled pipeline..."

      - name: Cleanup push flag
        if: always()
        run: rm -f push_flag.txt  # Remove flag after execution
