name: my first workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main, branch2
  
env:
  a : sachi
jobs:
  my_job:  
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello, $a !"  
  
  myjob_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
