on:
  push:
    branches:
      - main 

jobs:
  my_job:  
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello, GitHub Actions!"  

      - name: Checkout Repository
        uses: actions/checkout@v4