name: Scheduled Pipeline vol4 

on:
  push:
    
jobs:
  wait-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        run: |
          CURRENT_TIME=$(date +"%H:%M")
          echo "Current Time: $CURRENT_TIME"

          TARGET_TIME="10:05"

          while [ "$(date +"%H:%M")" != "$TARGET_TIME" ]; do
            echo "waiting for $TARGET_TIME"
            sleep 3600
          done

          echo "proceeding..."

      - name: Run workflow
        run: echo "Pipeline runs successfully at scheduled time"
